name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        npm install
        npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        slackToken: ${{ secrets.SLACK_TOKEN }}
        conversationId: ${{ secrets.SLACK_TEST_CONVERSATION_ID }}
        appName: 'Slack Deployment Notifcation Actions'
        envName: 'testing'
        refName: ${{ github.ref }}
    - run: sleep 10
    - uses: ./
      with:
        slackToken: ${{ secrets.SLACK_TOKEN }}
        conversationId: ${{ secrets.SLACK_TEST_CONVERSATION_ID }}

        status:
